version: "3.9"

networks:
  amplicode-addons-ldap-demo-r2-net:
    driver: bridge

services:
  amplicode-addons-ldap-demo-r2-postgres-12:
    container_name: amplicode-addons-ldap-demo-r2-postgres-12
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - amplicode-addons-ldap-demo-r2-net

  amplicode-addons-ldap-demo-r2-openldap:
    image: bitnami/openldap:2.5.9
    container_name: amplicode-addons-ldap-demo-r2-openldap
    environment:
      LDAP_ADMIN_DN: ${LDAP_ADMIN_USERNAME}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_ROOT: ${LDAP_ROOT}
      LDAP_CUSTOM_LDIF_DIR: "etc/ldifs"
    restart: unless-stopped
    volumes:
      - "../ldifs:/etc/ldifs/"
    ports:
      - "1389:1389"
      - "1636:1636"
    networks:
      - amplicode-addons-ldap-demo-r2-net

  amplicode-addons-ldap-demo-r2:
    container_name: amplicode-addons-ldap-demo-r2
    image: amplicode-addons-ldap-demo-r2:full
    restart: unless-stopped
    environment:
      RDS_HOSTNAME: amplicode-addons-ldap-demo-r2-postgres-12
      RDS_PASSWORD: ${DB_PASSWORD}
      RDS_USERNAME: ${DB_USERNAME}
      RDS_DB_NAME: ${DB_NAME}
      RDS_PORT: 5432
      LDAP_BASE_DN: ${LDAP_ROOT}
      LDAP_ADMIN_USERNAME: ${LDAP_ADMIN_USERNAME}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_HOSTNAME: amplicode-addons-ldap-demo-r2-openldap
      LDAP_PORT: 1389
      SPRING_PROFILES_ACTIVE: dev_docker
    depends_on:
      - amplicode-addons-ldap-demo-r2-postgres-12
      - amplicode-addons-ldap-demo-r2-openldap
    ports:
      - "8083:8080"
    networks:
      - amplicode-addons-ldap-demo-r2-net
