version: '3'

networks:
  amplicode-addons-ldap-demo-r2-net:
    driver: bridge

services:
  amplicode-addons-ldap-demo-r2-postgres-12:
    container_name: amplicode-addons-ldap-demo-r2-postgres-12
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${GRANT2_PASSWORD}
      POSTGRES_USER: ${GRANT2_USERNAME}
      POSTGRES_DB: ${GRANT2_NAME}
    networks:
      - amplicode-addons-ldap-demo-r2-net

  amplicode-addons-ldap-demo-r2-openldap:
    image: bitnami/openldap:2.5.9
    container_name: amplicode-addons-ldap-demo-r2-openldap
    environment:
      LDAP_ADMIN_DN: ${LDAP_ADMIN_USERNAME}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_ROOT: ${LDAP_ROOT}
      LDAP_CUSTOM_LDIF_DIR: "etc/ldifs"
    restart: unless-stopped
    volumes:
      - './ldifs:/etc/ldifs/'
    networks:
      - amplicode-addons-ldap-demo-r2-net

  amplicode-addons-ldap-demo-r2:
    container_name: amplicode-addons-ldap-demo-r2
    image: docker.haulmont.com/platform/infrastructure/demo-cuba-apps-docker/demo-r2/amplicode-addons-ldap-demo-r2:full
    restart: unless-stopped
    environment:
      RDS_HOSTNAME: amplicode-addons-ldap-demo-r2-postgres-12
      RDS_PASSWORD: ${GRANT2_PASSWORD}
      RDS_USERNAME: ${GRANT2_USERNAME}
      RDS_DB_NAME: ${GRANT2_NAME}
      RDS_PORT: 5432
      LDAP_BASE_DN: ${LDAP_ROOT}
      LDAP_ADMIN_USERNAME: ${LDAP_ADMIN_USERNAME}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_HOSTNAME: amplicode-addons-ldap-demo-r2-openldap
      LDAP_PORT: 1389
      SPRING_PROFILES_ACTIVE: docker
      APP_USERS_ADMIN_USERNAME: ${JMIX_ADMIN}
      APP_USERS_ADMIN_PASSWORD: ${JMIX_PASSWORD}
    depends_on:
      - amplicode-addons-ldap-demo-r2-postgres-12
      - amplicode-addons-ldap-demo-r2-openldap
    ports:
      - "8087:8080"
    networks:
      - amplicode-addons-ldap-demo-r2-net