spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
amplicode:
  ldap:
    base-dn: ${LDAP_BASE_DN}
    urls: ldap://${LDAP_HOSTNAME}:${LDAP_PORT}
    master-user-dn: cn=${LDAP_ADMIN_USERNAME},${LDAP_BASE_DN}
    master-user-password: ${LDAP_ADMIN_PASSWORD}
    standard-authentication-users: ${LDAP_STANDARD_USERS}
    user-props:
      search-base: ou=users
      username-attr: uid
    group-props:
      member-attr: member
      name-attr: cn
      search-base: ou=groups
    synchronization:
      enabled: true
      enabled-on-login: true
      perform-from-groups:
        - 'cn=developers,ou=groups,${LDAP_BASE_DN}'
        - 'cn=managers,ou=groups,${LDAP_BASE_DN}'
