spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amplicode-ldap-demo
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
amplicode:
  ldap:
    base-dn: dc=example,dc=com
    urls: ldap://localhost:10389
    master-user-dn: 'uid=admin,ou=system'
    master-user-password: secret
    enable-ldap-auth: on
    standard-authentication-users: admin, system
    user-props:
      search-base: ou=users
      username-attr: uid
    group-props:
      member-attr: member
      name-attr: cn
      search-base: ou=groups
    authorities-populator:
      search-in-subtrees: false
      convert-role-to-upper-case: true
      authority-name-prefix: ''
    synchronization:
      perform-from-groups:
        - 'cn=developers,ou=groups,dc=example,dc=com'
        - 'cn=managers,ou=groups,dc=example,dc=com'
      enabled: on
      enabled-on-login: on
    db-logging:
      level: info
      enabled: true
      logging-scopes: security, synchronization, listener
logging:
  level:
    com.amplicode: trace
