spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amplicode-ldap-demo
    username: root
    password: root
  liquibase:
    change-log: classpath:db/changelog.xml
  jpa:
    open-in-view: false
amplicode:
  ldap:
    base-dn: dc=amplicode,dc=com
    urls: ldap://localhost:1389
    standard-authentication-users: admin
    master-user-dn: 'cn=${amplicode.ldap.standard-authentication-users},${amplicode.ldap.base-dn}'
    master-user-password: admin
    user-props:
      search-base: ou=users
      username-attr: uid
    group-props:
      member-attr: member
      name-attr: cn
      search-base: ou=groups
    authorities-populator:
      authority-name-prefix: 'ROLE_'
      convert-role-to-upper-case: true
    synchronization:
      perform-from-groups:
        - 'cn=developers,ou=groups,dc=amplicode,dc=com'
        - 'cn=managers,ou=groups,dc=amplicode,dc=com'
      enabled: true
      enabled-on-login: true
    db-logging:
      enabled: true
      logging-scopes: security, synchronization, listener
logging:
  level:
    com.amplicode: trace

